// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: common.proto
package common;

import android.os.Parcelable;
import com.squareup.wire.AndroidMessage;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import okio.ByteString;

/**
 * 变更信息
 */
public final class BizAction extends AndroidMessage<BizAction, BizAction.Builder> {
  public static final ProtoAdapter<BizAction> ADAPTER = ProtoAdapter.newMessageAdapter(BizAction.class);

  public static final Creator<BizAction> CREATOR = AndroidMessage.newCreator(ADAPTER);

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_ACTION = 0L;

  public static final String DEFAULT_SNAME = "";

  public static final String DEFAULT_KEY = "";

  public static final ByteString DEFAULT_VALUE = ByteString.EMPTY;

  public static final Long DEFAULT_VALID_TIME = 0L;

  /**
   * see EBizAction
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long action;

  /**
   * Header.sname
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String sname;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String key;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString value;

  /**
   * 有效期，秒，相对时间，比如5表示5s后失效。如果没设置或者<=0表示永久有效
   */
  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long valid_time;

  public BizAction(Long action, String sname, String key, ByteString value, Long valid_time) {
    this(action, sname, key, value, valid_time, ByteString.EMPTY);
  }

  public BizAction(Long action, String sname, String key, ByteString value, Long valid_time,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.action = action;
    this.sname = sname;
    this.key = key;
    this.value = value;
    this.valid_time = valid_time;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.action = action;
    builder.sname = sname;
    builder.key = key;
    builder.value = value;
    builder.valid_time = valid_time;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BizAction)) return false;
    BizAction o = (BizAction) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(action, o.action)
        && Internal.equals(sname, o.sname)
        && Internal.equals(key, o.key)
        && Internal.equals(value, o.value)
        && Internal.equals(valid_time, o.valid_time);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (action != null ? action.hashCode() : 0);
      result = result * 37 + (sname != null ? sname.hashCode() : 0);
      result = result * 37 + (key != null ? key.hashCode() : 0);
      result = result * 37 + (value != null ? value.hashCode() : 0);
      result = result * 37 + (valid_time != null ? valid_time.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<BizAction, Builder> {
    public Long action;

    public String sname;

    public String key;

    public ByteString value;

    public Long valid_time;

    public Builder() {
    }

    /**
     * see EBizAction
     */
    public Builder action(Long action) {
      this.action = action;
      return this;
    }

    /**
     * Header.sname
     */
    public Builder sname(String sname) {
      this.sname = sname;
      return this;
    }

    public Builder key(String key) {
      this.key = key;
      return this;
    }

    public Builder value(ByteString value) {
      this.value = value;
      return this;
    }

    /**
     * 有效期，秒，相对时间，比如5表示5s后失效。如果没设置或者<=0表示永久有效
     */
    public Builder valid_time(Long valid_time) {
      this.valid_time = valid_time;
      return this;
    }

    @Override
    public BizAction build() {
      return new BizAction(action, sname, key, value, valid_time, super.buildUnknownFields());
    }
  }
}
