// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: common.proto
package common;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * ///////////////////////BIZ//////////////////////////////////
 * 用于控制变更行为
 */
public enum EBizAction implements WireEnum {
  BizActionNone(0),

  /**
   * 添加、修改（也就是覆盖）
   */
  BizActionAdd(1),

  /**
   * 删除
   */
  BizActionDel(2);

  public static final ProtoAdapter<EBizAction> ADAPTER = ProtoAdapter.newEnumAdapter(EBizAction.class);

  private final int value;

  EBizAction(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static EBizAction fromValue(int value) {
    switch (value) {
      case 0: return BizActionNone;
      case 1: return BizActionAdd;
      case 2: return BizActionDel;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
