// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: common.proto
package common;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum EBizType implements WireEnum {
  EBizTypeNone(0),

  EBizTypeAction(10),

  EBizTypeInfos(11),

  EBizTypeExt(12);

  public static final ProtoAdapter<EBizType> ADAPTER = ProtoAdapter.newEnumAdapter(EBizType.class);

  private final int value;

  EBizType(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static EBizType fromValue(int value) {
    switch (value) {
      case 0: return EBizTypeNone;
      case 10: return EBizTypeAction;
      case 11: return EBizTypeInfos;
      case 12: return EBizTypeExt;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
