// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: common.proto
package common;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * YMicro框架层返回码
 */
public enum YMicroRet implements WireEnum {
  /**
   * 成功
   */
  YMicroRetSuccess(0),

  /**
   * 请求非法
   */
  YMicroRetBadRequest(400),

  /**
   * 请求未鉴权
   */
  YMicroRetUnauthorized(401),

  /**
   * 请求被禁止
   */
  YMicroRetForbidden(403),

  /**
   * 请求后端服务未找到
   */
  YMicroRetNotFound(404),

  /**
   * 请求后端方法被禁止
   */
  YMicroRetMethodNotAllowed(405),

  /**
   * 请求冲突
   */
  YMicroRetConflict(409),

  /**
   * 内部服务错误
   */
  YMicroRetInternalServerError(500);

  public static final ProtoAdapter<YMicroRet> ADAPTER = ProtoAdapter.newEnumAdapter(YMicroRet.class);

  private final int value;

  YMicroRet(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static YMicroRet fromValue(int value) {
    switch (value) {
      case 0: return YMicroRetSuccess;
      case 400: return YMicroRetBadRequest;
      case 401: return YMicroRetUnauthorized;
      case 403: return YMicroRetForbidden;
      case 404: return YMicroRetNotFound;
      case 405: return YMicroRetMethodNotAllowed;
      case 409: return YMicroRetConflict;
      case 500: return YMicroRetInternalServerError;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
