// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: cproxy.proto
package ikxd.cproxy;

import android.os.Parcelable;
import com.squareup.wire.AndroidMessage;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import okio.ByteString;

public final class JoinRoomReq extends AndroidMessage<JoinRoomReq, JoinRoomReq.Builder> {
  public static final ProtoAdapter<JoinRoomReq> ADAPTER = ProtoAdapter.newMessageAdapter(JoinRoomReq.class);

  public static final Creator<JoinRoomReq> CREATOR = AndroidMessage.newCreator(ADAPTER);

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_ROOM_ID = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String room_id;

  public JoinRoomReq(String room_id) {
    this(room_id, ByteString.EMPTY);
  }

  public JoinRoomReq(String room_id, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.room_id = room_id;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.room_id = room_id;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof JoinRoomReq)) return false;
    JoinRoomReq o = (JoinRoomReq) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(room_id, o.room_id);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (room_id != null ? room_id.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<JoinRoomReq, Builder> {
    public String room_id;

    public Builder() {
    }

    public Builder room_id(String room_id) {
      this.room_id = room_id;
      return this;
    }

    @Override
    public JoinRoomReq build() {
      return new JoinRoomReq(room_id, super.buildUnknownFields());
    }
  }
}
