// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: cproxy.proto
package ikxd.cproxy;

import android.os.Parcelable;
import com.squareup.wire.AndroidMessage;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import okio.ByteString;

public final class ToastNotify extends AndroidMessage<ToastNotify, ToastNotify.Builder> {
  public static final ProtoAdapter<ToastNotify> ADAPTER = ProtoAdapter.newMessageAdapter(ToastNotify.class);

  public static final Creator<ToastNotify> CREATOR = AndroidMessage.newCreator(ADAPTER);

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_MSG = "";

  public static final Boolean DEFAULT_LOGOUT = false;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String msg;

  /**
   * 是否需要客户端退出登陆并删除token，用于踢人
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean logout;

  public ToastNotify(String msg, Boolean logout) {
    this(msg, logout, ByteString.EMPTY);
  }

  public ToastNotify(String msg, Boolean logout, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.msg = msg;
    this.logout = logout;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.msg = msg;
    builder.logout = logout;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ToastNotify)) return false;
    ToastNotify o = (ToastNotify) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(msg, o.msg)
        && Internal.equals(logout, o.logout);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (msg != null ? msg.hashCode() : 0);
      result = result * 37 + (logout != null ? logout.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ToastNotify, Builder> {
    public String msg;

    public Boolean logout;

    public Builder() {
    }

    public Builder msg(String msg) {
      this.msg = msg;
      return this;
    }

    /**
     * 是否需要客户端退出登陆并删除token，用于踢人
     */
    public Builder logout(Boolean logout) {
      this.logout = logout;
      return this;
    }

    @Override
    public ToastNotify build() {
      return new ToastNotify(msg, logout, super.buildUnknownFields());
    }
  }
}
