// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: cproxy.proto
package ikxd.cproxy;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum Uri implements WireEnum {
  kUriNone(0),

  kUriToastNotify(11),

  kUriJoinRoomReq(12),

  kUriJoinRoomRes(13),

  kUriLeaveRoomReq(14),

  kUriLeaveRoomRes(15),

  /**
   * 由于不同的websocket库不同，有些不支持心跳，因此心跳单独出来
   */
  kUriHeartbeatReq(16),

  kUriHeartbeatRes(17),

  /**
   * 探针，原样返回
   */
  kUriProbeNotify(18);

  public static final ProtoAdapter<Uri> ADAPTER = ProtoAdapter.newEnumAdapter(Uri.class);

  private final int value;

  Uri(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static Uri fromValue(int value) {
    switch (value) {
      case 0: return kUriNone;
      case 11: return kUriToastNotify;
      case 12: return kUriJoinRoomReq;
      case 13: return kUriJoinRoomRes;
      case 14: return kUriLeaveRoomReq;
      case 15: return kUriLeaveRoomRes;
      case 16: return kUriHeartbeatReq;
      case 17: return kUriHeartbeatRes;
      case 18: return kUriProbeNotify;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
